# Generated by Django 5.1.4 on 2025-01-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='permit',
            name='action',
            field=models.CharField(choices=[('OPEN', 'ОТКРЫТИЕ'), ('CLOSE', 'ЗАКРЫТИЕ')], default='ОТКРЫТИЕ', max_length=255),
        ),
    ]
