# Generated by Django 5.1.4 on 2025-01-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_signatures_alter_permit_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='signature_executor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись производителя'),
        ),
    ]
