# Generated by Django 5.1.4 on 2025-01-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_permit_signature_executor'),
    ]

    operations = [
        migrations.AddField(
            model_name='historypermit',
            name='signature_executor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись Executor'),
        ),
    ]
