# Generated by Django 5.1.4 on 2025-01-04 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_alter_privatekeys_private_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatekeys',
            name='private_key',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(50, 'the field must contain at least 50 characters')]),
        ),
    ]
